---
- name: PostgreSQL | Extensions | Add 2nd Quadrant repo gpg key | apt
  apt_key:
    url: "{{ repmgr_gpg_key_url }}"
  when: ansible_pkg_mgr == "apt" and repmgr_apt_repository_add

- name: PostgreSQL | Extensions | Add 2nd Quadrant repo for repmgr | apt
  apt_repository:
    repo: "{{ repmgr_apt_repository }}"
    filename: 2ndquadrant-dl-default-release
  when: ansible_pkg_mgr == "apt" and repmgr_apt_repository_add

- name: PostgreSQL | Extensions | Use specific version from repo | apt
  set_fact:
    repmgr_apt_name: "postgresql-{{ postgresql_version }}-repmgr={{ repmgr_version_debian }}"
  when: 
    - ansible_os_family == "Debian"
    - repmgr_version_debian is defined

- name: PostgreSQL | Extensions | Make sure the postgres repmgr extensions are installed | apt
  apt:
    name: "{{ repmgr_apt_name | default ('postgresql-' + postgresql_version|string + '-repmgr' ) }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time | default (3600) }}"
  when: ansible_pkg_mgr == "apt"
