---
- name: PostgreSQL | Ensure PostgreSQL is running
  shell: 
    cmd: pg_ctlcluster {{ postgresql_version }} {{ postgresql_cluster_name }} start
    executable: /bin/bash
  become: yes
  become_user: "{{ postgresql_service_user }}"
  register: postgresql_restart
  failed_when: postgresql_restart.rc not in [0, 2] # handle already-running return codes

- name: PostgreSQL | Make sure the PostgreSQL users are present
  postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.pass | default(omit) }}"
    encrypted: "{{ item.encrypted | default(omit) }}"
    port: "{{ postgresql_port }}"
    state: present
    login_user: "{{ postgresql_admin_user }}"
  # no_log: true
  become: yes
  become_user: "{{ postgresql_admin_user }}"
  with_items: "{{ postgresql_users }}"
  when: postgresql_users|length > 0 and repmgr_primary
